cmd/main.go
pkg/github/release.go

Useful for generating changelog for repos other than cilium/cilium.
Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

 Take "owner/repo" as a command-line parameter

---

cmd/projects/projects.go

This was saying you should try to release the version you're opening for
development, which doesn't make sense. Fix it.

projects: Fix start-release.sh command

---

pkg/github/labels.go
pkg/github/labels_test.go

Occasionally, new contributors will submit PRs and fail to fill out the
template. Sometimes it doesn't even make much sense to have a release
note, for instance when updating the USERS.md file or making some minor
change that the PR title already describes. For these cases, detect
whether the default string is in the release note and ignore it in favor
of the PR title instead.

pkg/github: Ignore unfilled release notes

---

.github/ISSUE_TEMPLATE/release_template_minor.md

Add a point to review the status of features in the upgrade guide,
roadmap so that the docs are consistent upon release.

.github: Mention upgrade/roadmap updates

---

.github/ISSUE_TEMPLATE/release_template_minor.md
.github/ISSUE_TEMPLATE/release_template_patch.md
.github/ISSUE_TEMPLATE/release_template_rc_branch.md
.github/ISSUE_TEMPLATE/release_template_rc_master.md

Recent commits in cilium/cilium have rendered this step unnecessary for
the most common releases. For RCs and main releases we may still need to
manually fix some things up.

.github: Update templates for crd check automation

---

.github/ISSUE_TEMPLATE/release_template_patch.md
.github/ISSUE_TEMPLATE/release_template_rc_branch.md

We don't need these steps for making new v1.9 releases any more, since
the Cilium project only creates v1.10, v1.11, v1.12 releases now.

.github: Remove references to v1.9 branches

---

.github/ISSUE_TEMPLATE/release_template_rc_master.md

This step should no longer be necessary if using the master (to be 1.13)
version of the CRD schema script due to the commit in the cilium repository
48f81350cda9 ("docs/crd: Support master RCs in schema bump script").
Related: https://github.com/cilium/cilium/pull/21535

.github: Remove CRD schema extra step for RCs

---

.github/ISSUE_TEMPLATE/release_template_patch.md

Maintainers typically know whether there is an important outstanding
issue that is being solved, security patches that are queued up but not
merged, or may have access to additional testing dashboards to provide
feedback on the whether the release is "good to go". This step is a
catch all to ask maintainers about these topics and sync up before
triggering the remaining release automation.

.github: Add pre-tag sanity check to patch releases

---

.github/ISSUE_TEMPLATE/release_template_minor.md
.github/ISSUE_TEMPLATE/release_template_patch.md
.github/ISSUE_TEMPLATE/release_template_rc_branch.md
.github/ISSUE_TEMPLATE/release_template_rc_master.md

This PR contains some updates to the release templates, following the October 2022 patch releases round. Probably easier to review per commit: Each commit brings a single change to the patch release template, then the last commit reports the relevant changes to the other templates too.
Changes can be visualised at https://github.com/qmonnet/release/issues/new/choose.
I have not updated the related docs at docs.cilium.io yet.

Miscellaneous updates to the release templates

---

cmd/main.go
cmd/projects/projects.go

As part of backport tracking, we set labels on PRs and attempt to ensure
that when a backport is "done" for a branch, the labels are set and this
controls which column in the versioned project that the PR ends up in.
When we do a new release, the previous behaviour of this tool was to
move all "pending" backports to the project for the next release
version. However, sometimes an earlier step is missed, which means that
PRs that have already been backported eg to 1.12.4 are marked as
"pending" in 1.12.4. This tool then mistakenly moves them to
"pending to 1.12.5", which is incorrect and confusing.
In the absence of a better system to control these, at least avoid
propagating the mistake in this tool. By default, prevent the release
manager from moving "pending backports" to a new project. …

Avoid moving pending backports to new project

---

pkg/github/labels.go
pkg/github/labels_test.go

Some backport managers prefer to remove the prompt symbol ($) from the upstream-prs block in the description of backport PRs, because it makes it easier to copy the command to paste it into a terminal (we can use GitHub's copy button, and then there's no prompt symbol to trim before pasting).
This is not currently compatible with how the release tool works, but we can update it accordingly.
Update the tests with a few related cases, and add real test names to avoid re-numbering all tests.
Reference: https://github.com/cilium/cilium/pull/23515#issuecomment-1427536231

Work when prompt symbol is missing from upstream-prs block

---

.github/ISSUE_TEMPLATE/release_template_rc_branch.md
.github/ISSUE_TEMPLATE/release_template_rc_master.md

This was recently rendered unnecessary due to changes to this Makefile;
the changes were automatically rendered into the Helm charts.

Improve the RC steps for latest process

---

cmd/main.go

Similar to the "NOTE" message, we should also print the PRs that will not be part of the changelog into the stderr, otherwise they might be part of the official changelog in case we are redirecting the output of the release notes creation into a file.
Fixes https://github.com/cilium/release/issues/96

release: print PRs from last-stable to stderr

---

.github/ISSUE_TEMPLATE/release_template_minor.md
.github/ISSUE_TEMPLATE/release_template_patch.md
.github/ISSUE_TEMPLATE/release_template_rc_branch.md
.github/ISSUE_TEMPLATE/release_template_rc_master.md

This link will select the necessary permissions automatically in order to perform the release process.

.github: add direct link to generate GH token

---

.github/ISSUE_TEMPLATE/release_template_rc_branch.md
pkg/github/labels.go

After the introduction of the GH workflow Backport Label Updater, there is no need to manually update the labels of each Backport PR in OSS. The generated text asking to manually update the labels in the Backport PR has been removed, so the code to fetch the PRs numbers is updated accordingly.
Also, the PR adds a task in the Pre-release checklist to create a new workflow for the stable branch to call the Backport Label Updater once a Backport PR is merged.
Depends on: https://github.com/cilium/cilium/pull/27875

Update backport docs after update-label workflow

---

.github/ISSUE_TEMPLATE/release_template_patch.md
.github/ISSUE_TEMPLATE/release_template_rc_branch.md
.github/ISSUE_TEMPLATE/release_template_rc_master.md

Newer changes in the Cilium tree allow the same script to be used for
patch releases and prereleases.
Depends on https://github.com/cilium/cilium/pull/27892

Streamline the readme bump for all release types

---

pkg/github/labels.go
pkg/github/labels_test.go

The generated text asking to manually update the labels in the Backport
PRs has been removed and the getUpstreamPRs has been updated accordingly
in a previous commit.
Nevertheless, there will be a window where cilium/release will have to
parse Backport PRs with the "old" (v1) body format alongside Backport
PRs with the "new" (v2) body format.
An example of the v1 body format is this:
```
for pr in 9959 9982 10005; do contrib/backporting/set-labels.py $pr done 1.6; done
```
While the v2 body format is simply a space separated list of backported
PRs:
```
9959 9982 10005
```
This commit extends the getUpstreamPRs function to look for text
patterns that should be present only in "v1" body format and then try to
parse the block using the parser for the guessed format.
The unit test has been …

Support v1 and v2 format when parsing Backport PRs

---

.github/ISSUE_TEMPLATE/release_template_rc_branch.md

Using bpf-next lvh images in stable branches leads to additional developer burden since bpf-next does contain regressions from time to time. Instead, switch to the latest LTS at the time of branching.
Note that is it important that we keep updating the base images, since changes in lvh can break old images.

RC branch: remove references to bpf-next lvh images

---

.github/ISSUE_TEMPLATE/release_template_minor.md

This is done automatically for all the other releases, but seems to need
manual intervention for the minor release. Add it to the checklist until
we automate this step.
Fixes: #190

.github: Add the step to update stable.txt

---

cmd/projects/sync.go

Set the "force-move-pending-backports" flag to default to true. All pending backports should be moved.

cmd: Force Move All Pending Backports

---

cmd/checklist/open.go

This output line was printing the wrong link, and missing a newline
afterwards. Fix it so that it provides a human-readable link to follow.

cmd: Fix checklist output

---

.github/ISSUE_TEMPLATE/release_template_minor.md
.github/ISSUE_TEMPLATE/release_template_patch.md
.github/ISSUE_TEMPLATE/release_template_rc_branch.md
.github/ISSUE_TEMPLATE/release_template_rc_master.md

We no longer need to pull the charts, because the new tool pulls the
charts directly from the Cilium tree.
See also https://github.com/cilium/charts/pull/114

Update release process for new Helm chart tool

---

.github/ISSUE_TEMPLATE/release_template_patch.md

Now Renovate takes care of bumping base / runtime images. I boldly assert that release managers should not be responsible for updating dependencies anyways.

patch: Remove the step to bump base / runtime images

---

.github/ISSUE_TEMPLATE/release_template_minor.md
.github/ISSUE_TEMPLATE/release_template_patch.md
.github/ISSUE_TEMPLATE/release_template_rc_branch.md
.github/ISSUE_TEMPLATE/release_template_rc_master.md

- Point to RELEASE.md instead of generate_helm_release.sh. RELEASE.md contains instructions for using the script.
- conformance-gke.yaml has been replaced by validate-cilium-chart.yaml.
Ref: https://github.com/cilium/charts/pull/114
Ref: https://github.com/cilium/charts/pull/125

Update links in cilium/charts repo

---

.github/ISSUE_TEMPLATE/release_template_minor.md
.github/ISSUE_TEMPLATE/release_template_patch.md
.github/ISSUE_TEMPLATE/release_template_rc_branch.md
.github/ISSUE_TEMPLATE/release_template_rc_master.md
internal/bump-readme.sh
internal/lib/common.sh
internal/lib/gitlib.sh
internal/lib/k8s-common.sh
internal/post-release.sh
internal/prep-changelog.sh
internal/pull-docker-manifests.sh
internal/start-release.sh
internal/submit-release.sh
internal/tag-release.sh

**NOT** easier to review per commit.
To diff against [André's branch](https://github.com/cilium/release/tree/pr/add-release-scripts).
Recipe:
```bash
cd cilium
rm contrib/release/bump-docker-stable.sh contrib/release/check-docker-images.sh
git format-patch 7fa3c60eb7dbe7a5a4caea3aab0396f75a8b10c7 -o /tmp/foo contrib/release/**/** contrib/backporting/common.sh
cd ../release
git switch -c new-branch
git am -p3 --directory=internal /tmp/foo/*
git filter-branch -f --tree-filter "git mv -kf internal/lib/common.sh internal/lib/k8s-common.sh" master..
git filter-branch -f --tree-filter "git mv -kf internal/common.sh internal/lib/common.sh" master..
git filter-branch -f --msg-filter "sed '2a [ cherry-picked from cilium/cilium repository ]\n'" master..
gh pr checkout 206
git checkout -
git …
```

Add scripts to perform Cilium releases, with Git history included

---

internal/post-release.sh

In my env, the command `tail -n+4 CHANGELOG.md | sed '/^## v.*$/q'` includes the version header of the previous command. Grep it out.
% tail -n+4 CHANGELOG.md | sed '/^## v.*$/q'
Summary of Changes
------------------
**Minor Changes:**
...
* Revert golang image version of hubble-relay (cilium/cilium#32732, @YutaroHayakawa)

Grep out version header while generating release notes

---

.github/ISSUE_TEMPLATE/release_template_rc_branch.md

While preparing the branching for v1.16 some steps were out of date. This commit adds some new changes for the next 1.17 branching.

.github: re-write some RC branch steps

---

internal/pull-docker-manifests.sh

We have more than 30 artifacts on docker build images. The default number of results per page that GitHub returns is 30. To avoid the release script from failing we need to increase the number of artifacts per page more than 100.

internal: fix pull-docker-manifests

---

cmd/changelog/changelog.go
cmd/changelog/generate.go
cmd/main.go

--exclude-pr-references configures the `release` tool to not include references to pull requests in the generated changelog.
We have some internal projects that we would like to re-use the cilium/release tooling for, but since the projects are private, the references to the PR, repository and author is a bit unnecessary, and potentially confusing to end-users, so this PR adds an option to not include that information in the generated changelog.

changelog: Add --exclude-pr-references option

---

.github/ISSUE_TEMPLATE/release_template_rc_branch.md

Add the steps to update the call-backport-label-updater workflows in the Pre-release checklist.
Related: https://github.com/cilium/cilium/pull/29902#issuecomment-1878365319

Add Pre-release steps to update call-backport-label-updater workflow

---

cmd/changelog/generate.go

Previously, if a PR was merged upstream and then a backport created from
it, the tool would incorrectly output the backport / upstream PRs in the
wrong order, implying that the PR that is actually upstream is the one
that is the backport, and vice versa. Fix it.

changelog: Fix backport/upstream PR ordering

---

cmd/changelog/changelog.go
cmd/changelog/generate.go
cmd/main.go

We're using the release tool to generate new markdown docs files and want insert our own header and then append the output of release to generate the release changelog, so add an option to skip printing the "Summary of Changes" header at the top.

Add flag to skip printing summary header

---

cmd/changelog/generate.go

Add support for organizing security updates in release notes into their own section. We're looking at using `cilium/release` for some internal projects and having a way to organize security updates/fixes separately from the other updates would be useful, so add support for a `release-note/security` label.

Add support for release-note/security label

---

.github/ISSUE_TEMPLATE/release_template_rc_branch.md

This reverts commit f5fd1137592728eaa6b9167c245d4199079358c0.
These steps are no longer necessary, as the workflow has been generalized to not explicitly include the list of branches.
Related: cilium/cilium#33934

Revert ".github: Pre-release backport-label-updater steps"

---

.github/ISSUE_TEMPLATE/release_template_patch_new.md

Fixes: 0b00175dc804 (".github: Add Slack announcement text templates")

.github: Fix template formatting for announcements

---

cmd/changelog/changelog.go
cmd/changelog/generate.go
cmd/changelog/labels.go
cmd/changelog/labels_test.go
cmd/main.go
pkg/github/release.go
pkg/types/pull_request.go

Partially reverts the behavior change introduced by https://github.com/cilium/release/pull/238.
Filtering is still done in the changelog generation, but now we store all of the PR labels in the release-state and return to filtering against all the PR labels using --label-filter.
The newly introduced behavior in #238 is now part of the new --release-labels flag, which configures the release-labels to use when generating release notes.
CC @michi-covalent who noticed the behavior change.
This does require deleting your existing `release-state.json` since all PR labels are now being stored in the release-state.
```
(⎈|kind-kind:N/A) ~/p/w/cilium-oss ❯❯❯ GITHUB_TOKEN=$(gh auth token) /Users/chancez/projects/work/release/release changelog --base v1.16.0-pre.3 --head v1.16.0 --repo cilium/cilium …
```

Differentiate between label-filter and release labels

---

.github/assets/logo.svg
README.md
cmd/changelog/changelog.go
cmd/main.go

- Add logo to repository
- README.md: Expand doc, tell how to generate release notes
- changelog: Fix typo (duplicate 'of') in command help
- README.md: Remove outdated instruction for GITHUB_TOKEN

README improvements + typo fix

---

cmd/changelog/generate.go

Initialize a nil map before writing to it.
From https://github.com/cilium/cilium/actions/runs/10349027982/job/28642554669:
panic: assignment to entry in nil map
goroutine 1 [running]:
github.com/cilium/release/cmd/changelog.(*ChangeLog).PrintReleaseNotesForWriter(0xc0005f6270, {0xb0e140, 0xc0003a4090})
/home/runner/work/cilium/release/cmd/changelog/generate.go:181 +0x170e
github.com/cilium/release/cmd/release.(*PrepareCommit).generateChangeLog(0xc000058128, {0xb12260, 0xc00007cb90}, 0xc0001e2b90)
/home/runner/work/cilium/release/cmd/release/git.go:244 +0x40c
github.com/cilium/release/cmd/release.(*PrepareCommit).Run(0xc000058128, {0xb12260, 0xc00007cb90}, 0x5f?, 0x25?, 0xc0001e2b90)
/home/runner/work/cilium/release/cmd/release/git.go:139 +0xc65 …

changelog: Do not add to a nil map

---

cmd/checklist/open.go

PR adds a sanitization step in `checklist open` to prevent creating checklists for an already released version.
Since that requires checking `cilium/cilium` while the rest of the command works with `cilium/release`, it gets a bit awkward with the flags. Suggestions welcome of how to make this more usable.

checklist: check if release already exists

---

cmd/changelog/generate.go
pkg/github/labels.go
pkg/github/labels_test.go

This fixes the changelog output so it removes both it handles both `\n` and `\r\n`. I was finding that when I was outputting changelogs to a file, there were `^M` invisible characters in the output. This is because the previous code was only replacing `\n` but not the `\r`. When I query the GitHub API, newlines are typically delimited as `\r\n` so the code should accommodate this case. `bufio.Scanner` is designed to handle reading text line by line already, so I adapted the `textBlockBetween` to use `buffo.Scanner` while preserving existing behavior.

Remove all newlines from changelog item output

---

.github/ISSUE_TEMPLATE/release_template_patch.md

This needs to be manual for now apparently because of the issue documented here:
https://github.com/cilium/release/blob/0a6859a0cd119cd8390ef861a075b6289c8cacaa/cmd/release/projects.go#L159-L160

.github: Add step to release to close GH projects

---

.github/ISSUE_TEMPLATE/release_template_pre_main.md
.github/ISSUE_TEMPLATE/release_template_rc_branch.md
Makefile
cmd/checklist/open.go
cmd/checklist/template.go
cmd/checklist/template_test.go
testdata/checklist/release_template_minor.md.golden
testdata/checklist/release_template_minor.md.input
testdata/checklist/release_template_patch.md.golden
testdata/checklist/release_template_patch.md.input
testdata/checklist/release_template_pre_main.md.golden
testdata/checklist/release_template_pre_main.md.input
testdata/checklist/release_template_rc_branch.md.golden
testdata/checklist/release_template_rc_branch.md.input

Fix a bug where release issue templates would be truncated before posting them
to GitHub whenever they included a horizontal separator (`---`).
While we're at it, add tests for the templating functionality to ensure that
the templates are processed correctly to generate issues with all version
numbers substituted. Use golden tests for this (generate with `make
generate-golden`). This also required updating the templates to match the
version substitutions supported by the checklist open command.
Review commit-by-commit.
Fixes: #256
Fixes: #261

Fix truncated checklist issue generation

---

cmd/changelog/generate.go

I forgot to handle this case in #198.
Fixes: f56f58f7b409 ("Include repo name in release note entries")

Include repo name in backport PR entries

---

.github/ISSUE_TEMPLATE/templates.go
cmd/checklist/open.go
cmd/checklist/template.go

This allows the tool to autodetect the right template based on
the specified version rather than having to specify the path,
for example `./release --version v1.17.0`.

Autodetect checklist template based on target version

---

testdata/checklist/release_template_rc_branch.md.golden

Fix release build error:
```
?       github.com/cilium/release/cmd   [no test files]
ok      github.com/cilium/release/cmd/changelog (cached)
--- FAIL: Test_prepareChecklist (0.00s)
--- FAIL: Test_prepareChecklist/release_template_rc_branch.md (0.00s)
template_test.go:104:
Error Trace:    /Volumes/dev/cilium/release/cmd/checklist/template_test.go:104
Error:          Not equal:
...
```

regenerate golden test files to fix test breakage.

---

internal/bump-readme.sh

Before this commit, a single check for all lines matching a release
table would detect both the stable releases and development releases,
which have different table sizes. This would cause the script to
incorrectly inform the user that they need to check the malformed table.
Fix this by doing two separate checks, one for the stable release table
and one for the pre-release table.
Before:
```
$ ../cilium-release/internal/bump-readme.sh                                                                                                                             
The following table is malformed, please fix it: …
```

bump-readme: Fix table misformatting detection

---

.github/ISSUE_TEMPLATE/release_template_rc_branch.md
testdata/checklist/release_template_rc_branch.md.golden
tools/bump-readme/main.go

Many of these instructions were vague or unnecessary; this commit
clarifies many of them and points out specific commands that can be used
to achieve the individual step. This is one step closer to automating
the branch creation.
Signed-off-by: Joe Stringer <joe@cilium.io>

.github: Improve branching instructions

---

cmd/changelog/changelog.go
cmd/changelog/generate.go
cmd/release/git.go
cmd/release/start.go

This will be useful to exclude certain PRs from changelogs when they are
unrelated to the target release.
Related: https://github.com/cilium/release/issues/272

changelog: Add --exclude-labels flag
